version: 2
jobs:
  checkout-source:
    docker:
      - image: cimg/base:stable
    working_directory: /home/circleci/karto
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - karto
  build-front:
    docker:
      - image: cimg/node:12.16.3
    working_directory: /home/circleci/karto
    steps:
      - attach_workspace:
          at: /home/circleci
      - restore_cache:
          keys:
            - v4-front-dependencies-{{ checksum "front/package.json" }}
            - v4-front-dependencies-
      - run:
          working_directory: front
          name: Download dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - front/node_modules
            - /home/circleci/.cache/yarn/v6
          key: v4-front-dependencies-{{ checksum "front/package.json" }}
      - run:
          working_directory: front
          name: Run tests
          command: yarn test
      - run:
          working_directory: front
          name: Build frontend
          command: yarn build
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - karto/front/build
  build-back:
    docker:
      - image: cimg/go:1.14.2
    working_directory: /home/circleci/karto
    steps:
      - attach_workspace:
          at: /home/circleci
      - restore_cache:
          keys:
            - v4-back-dependencies-{{ checksum "back/go.sum" }}
            - v4-back-dependencies-
      - run:
          working_directory: back
          name: Run tests
          command: go test ./...
      - run:
          working_directory: back
          name: Build backend
          command: |
            go install github.com/markbates/pkger/cmd/pkger && pkger
            export CGO_ENABLED=0
            go build karto
            GOOS=darwin GOARCH=amd64 go build -o karto_darwin
            GOOS=windows GOARCH=amd64 go build -o karto.exe
      - save_cache:
          key: v4-back-dependencies-{{ checksum "back/go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - store_artifacts:
          path: back/karto
      - store_artifacts:
          path: back/karto_darwin
      - store_artifacts:
          path: back/karto.exe
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - karto/back/karto
  dockerize-and-release:
    docker:
      - image: cimg/base:stable
    working_directory: /home/circleci/karto
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Build docker image
          command: |
            docker build -t zenikalabs/karto .
            docker tag zenikalabs/karto zenikalabs/karto:v1
            docker tag zenikalabs/karto zenikalabs/karto:v1.2
            docker tag zenikalabs/karto zenikalabs/karto:v1.2.1
      - run:
          name: Push docker image
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker push zenikalabs/karto
            docker push zenikalabs/karto:v1
            docker push zenikalabs/karto:v1.2
            docker push zenikalabs/karto:v1.2.1
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - checkout-source
      - build-front:
          requires:
            - checkout-source
      - build-back:
          requires:
            - build-front
      - dockerize-and-release:
          requires:
            - build-back
          filters:
            branches:
              only: release
