---
apiVersion: v1
kind: Namespace
metadata:
  name: network-policy-explorer
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: network-policy-explorer
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: network-policy-explorer
  name: network-policy-explorer
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: network-policy-explorer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: network-policy-explorer
subjects:
  - kind: ServiceAccount
    namespace: network-policy-explorer
    name: network-policy-explorer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-policy-explorer
  namespace: network-policy-explorer
  labels:
    app.kubernetes.io/name: network-policy-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: network-policy-explorer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: network-policy-explorer
    spec:
      serviceAccountName: network-policy-explorer
      containers:
        - name: app
          imagePullPolicy: Always
          image: zenikalabs/network-policy-explorer
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 1000m
              memory: 50Mi
